spring:
  application:
    name: szs
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:spacewalk;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  token:
    secret: "YnV2YWJiY3ZkZdlrisIe8KDh3D2D3JDs82GVdkdu5seDMW27C5n26dmZ2hpamtsbW5vcHFycw=="

springdoc:
  swagger-ui:
    path: /3o3/swagger.html
